# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 19:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='rss_link',
            new_name='rss_url',
        ),
        migrations.AddField(
            model_name='article',
            name='feed',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='news.Feed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
