# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 07:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20160425_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='text',
        ),
    ]
