# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_preview_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_photo',
            field=models.ImageField(default='', upload_to='media/blog/img/previews'),
        ),
    ]
