# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_custom_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='custom_url',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
