# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160229_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='custom_url',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
